#!/bin/bash
# cleanup.sh - Workspace cleanup script for robot_ws
#
# This script ONLY cleans build/, install/, log/
# It does NOT delete any source packages in src/
#
# Usage:
#   bash cleanup.sh          # Show what will be cleaned (dry run)
#   bash cleanup.sh --run    # Actually clean
#
# After running, rebuild with:
#   cd ~/robot_ws && colcon build

set -e

WORKSPACE="$HOME/robot_ws"
DRY_RUN=true

if [ "${1}" = "--run" ]; then
    DRY_RUN=false
fi

echo "=========================================="
echo "  robot_ws Workspace Cleanup"
echo "=========================================="
echo ""

# ---- Analyze disk usage ----
echo "=== Current disk usage ==="
du -sh "$WORKSPACE/build/" 2>/dev/null || echo "  build/ not found"
du -sh "$WORKSPACE/install/" 2>/dev/null || echo "  install/ not found"
du -sh "$WORKSPACE/log/" 2>/dev/null || echo "  log/ not found"
echo ""

# ---- Check for orphaned build artifacts ----
echo "=== Orphan check ==="
echo "Packages in build/ but NOT in src/:"
for dir in "$WORKSPACE/build/"*/; do
    pkg=$(basename "$dir")
    if [ ! -d "$WORKSPACE/src/$pkg" ]; then
        echo "  ORPHAN: $pkg (source no longer exists)"
    fi
done
echo ""

echo "Packages in install/ but NOT in src/:"
for dir in "$WORKSPACE/install/"*/; do
    pkg=$(basename "$dir")
    if [ ! -d "$WORKSPACE/src/$pkg" ] && [ -d "$dir" ]; then
        echo "  ORPHAN: $pkg (source no longer exists)"
    fi
done
echo ""

# ---- Log directory analysis ----
LOG_COUNT=$(find "$WORKSPACE/log/" -maxdepth 1 -type d -name "build_*" | wc -l)
echo "=== Log directory ==="
echo "  Build log sessions: $LOG_COUNT"
echo ""

# ---- Action plan ----
echo "=========================================="
echo "  Cleanup Plan"
echo "=========================================="
echo ""
echo "WILL CLEAN:"
echo "  1. build/    - All build artifacts (safe to delete, regenerated by colcon build)"
echo "  2. install/  - All installed files (safe to delete, regenerated by colcon build)"
echo "  3. log/      - $LOG_COUNT build log sessions (historical logs, not needed)"
echo ""
echo "WILL NOT TOUCH:"
echo "  - src/       - All source packages (your code is safe)"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo "=========================================="
    echo "  DRY RUN - No changes made"
    echo "=========================================="
    echo ""
    echo "To actually clean, run:"
    echo "  bash $0 --run"
    exit 0
fi

# ---- Execute cleanup ----
echo "=========================================="
echo "  Executing cleanup..."
echo "=========================================="
echo ""

# Clean build/
echo "[1/3] Cleaning build/..."
if [ -d "$WORKSPACE/build/" ]; then
    find "$WORKSPACE/build/" -mindepth 1 -delete
    echo "  Done."
else
    echo "  Skipped (not found)."
fi

# Clean install/
echo "[2/3] Cleaning install/..."
if [ -d "$WORKSPACE/install/" ]; then
    find "$WORKSPACE/install/" -mindepth 1 -delete
    echo "  Done."
else
    echo "  Skipped (not found)."
fi

# Clean log/
echo "[3/3] Cleaning log/..."
if [ -d "$WORKSPACE/log/" ]; then
    find "$WORKSPACE/log/" -mindepth 1 -delete
    echo "  Done."
else
    echo "  Skipped (not found)."
fi

echo ""
echo "=========================================="
echo "  Cleanup complete!"
echo "=========================================="
echo ""
echo "Next step: Rebuild workspace"
echo "  cd ~/robot_ws"
echo "  source /opt/ros/humble/setup.bash"
echo "  colcon build"
echo "  source install/setup.bash"
