; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
; Cấu hình tốc độ Nạp (Upload Speed) - Thường dùng 921600 để nạp nhanh hơn
upload_speed = 921600

; Cấu hình tốc độ Monitor (Serial Monitor Baud Rate)
monitor_speed = 115200
monitor_filters = send_on_enter

; Tự động chọn cổng COM nạp và cổng Serial Monitor
upload_port = COM*
monitor_port = COM*

; Cấu hình Trình biên dịch (Compiler Flags)
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    -O2                             ; Tối ưu hóa hiệu năng code
    -D CORE_DEBUG_LEVEL=3           ; Bật Log mức Info để dễ debug
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0    ; Route standard Serial to hardware UART0 (COM5)
    -I$PROJECT_DIR/include
    -I$PROJECT_DIR/src
    -I$PROJECT_DIR/lib/Core
    -I$PROJECT_DIR/lib/Interfaces
    -I$PROJECT_DIR/lib/Control
    -I$PROJECT_DIR/lib/Encoder
    -I$PROJECT_DIR/lib/ROS2Protocol
    -I$PROJECT_DIR/lib/Sensor_HC_SR04
    -I$PROJECT_DIR/lib/Motor
    -I$PROJECT_DIR/lib/Mpu6050
    -I$PROJECT_DIR/lib/BLEManager
lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    BTS7960
    MH_FMD
    Motor
    Mpu6050
    ROS2Protocol
    Sensor_HC_SR04
    Encoder
    h2zero/NimBLE-Arduino @ ^1.4.2
