[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    adafruit/MPU6050 @ ^1.13.0
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_JSON_USE_LONG_LONG=0

src_dir = src

[env:test_motor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DTEST_MOTOR

src_dir = src/test_motor

[env:test_sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DTEST_SENSOR

src_dir = src/test_sensor
